### ISSUE TITLE
Errors in the Read Me.

### ISSUE THREAD

**Issue by majortom64** [adam-fowler/aws-cognito-authentication#19]
The example: 

```
let awsCognitoConfiguration = CognitoConfiguration(
    userPoolId: String = "eu-west-1_userpoolid",
    clientId: String = "23432clientId234234",
    clientSecret: String = "1q9ln4m892j2cnsdapa0dalh9a3aakmpeugiaag8k3cacijlbkrp",
    cognitoIDP: CognitoIdentityProvider = CognitoIdentityProvider(region: .euwest1), adminClient: true
)
```

CognitoIdentityProvider needs an awsClient as one of its arguments:

`CognitioIdentityProvider(client: awsClient, region: .euwest1)
`
Also, the example calls for `adminClient: true`, but the code says that is an extra argument (I presume that something got updated but the vapor version did not yet).

**Comment by adam-fowler** [comment]
Fixed the client in the `CognitoIdentityProvider` init
The `adminClient` parameter is valid you just need to be on the right version of the code
